// Generated by spider on 2021-04-11 10:05:35.268871

part of 'resources.dart';

class Images {
  Images._();

  static const String thirdIntro = 'assets/images/third_intro.png';
  static const String logoSplash = 'assets/images/logoSplash.png';
  static const String usa = 'assets/images/usa.png';
  static const String appleButton = 'assets/images/appleButton.png';
  static const String facebookButton = 'assets/images/facebookButton.png';
  static const String username = 'assets/images/username.png';
  static const String password = 'assets/images/password.png';
  static const String logo = 'assets/images/logo.png';
  static const String googleButton = 'assets/images/googleButton.png';
  static const String secondIntro = 'assets/images/second_intro.png';
  static const String firstIntro = 'assets/images/first_intro.png';
  static const String vietnam = 'assets/images/vietnam.png';
}
